#' @title myclt
#'
#' @param n sample size
#' @param iter number of iterations
#'
#' @return a histogram depicting the average sum within a column of data
#' generated by n and iter and a vector of its values
#' @export
#'
#' @examples
#' myclt(n = 10, iter = 10000)
myclt = function(n, iter) {
  y = runif(n*iter, 0, 5)
  data = matrix(y, nr = n, nc = iter, byrow=TRUE)
  sm = apply(data, 2, sum)
  hist(sm)
  sm
}
